name = input()
c = int(input())
v = int(input())
d = int(input())
print('================Чек================')
print(f"Товар:{name: >29}")
print(f"Цена:{str(v) + 'кг * ' + str(c) + 'руб/кг': >30}")
print(f"Итого:{str(c * v) + 'руб': >29}")
print(f"Внесено:{str(d) + 'руб': >27}")
print(f"Сдача:{str(d - c * v) + 'руб': >29}")
print('=' * 35)
