name = input()
c = int(input())
v = int(input())
d = int(input())
print('Чек')
print(f"{name} - {v}кг - {c}руб/кг")
print(f"Итого: {c * v}руб")
print(f"Внесено: {d}руб")
print(f"Сдача: {d - c * v}руб")